Hi everyone! let's make customer churn predictions with machine learning this is my task 3 in codsoft as a machine learning intern -SREEKUMAR S


Task :
Develop a model to predict customer churn for a subscription-based service or business. Use historical customer data, includingfeatures like usage behavior and customer demographics, and tryalgorithms like Logistic Regression, Random Forests, or GradientBoosting to predict churn.

#first, let's import the necessary libraries

In [1]:
import pandas as pd #for data manipulation and analysis
import numpy as np #for numerical calculations in python
from sklearn.model_selection import train_test_split #this is function is like for splitting the data into training and testing
from sklearn.preprocessing import StandardScaler #for standardized the features
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier #ensemble decision tree in sequentially to correct errors of previous one
from sklearn.linear_model import LogisticRegression #i am using this linearmodel has this task be binary classification
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, accuracy_score #model evaluate model performance
from sklearn.utils import resample


# second, let's import the dataset

In [8]:
data = pd.read_csv('/content/Churn_Modelling.csv')
data.head(10) #first 10lines of dataset for understanding purpose

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [9]:
data.info() #this is a summary of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [10]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

from this we can understand dataset as no null values so this is cleaned dataset


In [11]:
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1) #removing unnecessary features

In [12]:
data = pd.get_dummies(data, columns=['Geography', 'Gender'], drop_first=True) #encode of categorical values

#third, let's Split Features and Target Variables

In [13]:
X = data.drop('Exited', axis=1) # the x variable have all features expect feature exited
y = data['Exited'] #y variable have exited variable values only



#Fourth, let's split the data into train and test


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Fifth, let's standardize the features

In [15]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Sixth, let's Train Logistic Regression model

In [16]:
log = LogisticRegression(random_state=42)
log.fit(X_train, y_train)
y_pred0 = log.predict(X_test)
log_acc = accuracy_score(y_test, y_pred0)
print(f'Logistic Regression Accuracy: {log_acc:.4f}')
print(classification_report(y_test, y_pred0))

Logistic Regression Accuracy: 0.8110
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.55      0.20      0.29       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000



#seveth, let's Train Random Forest model

In [17]:
random = RandomForestClassifier(n_estimators=100, random_state=42)
random.fit(X_train, y_train)
y_pred1 = random.predict(X_test)
random_acc = accuracy_score(y_test, y_pred1)
print(f'Random Forest Accuracy: {random_acc:.4f}')
print(classification_report(y_test, y_pred1))

Random Forest Accuracy: 0.8665
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000



#8, let's Train Gradient Boosting model

In [18]:
gradient = GradientBoostingClassifier(n_estimators=100, random_state=42)
gradient.fit(X_train, y_train)
y_pred2 = gradient.predict(X_test)
gradient_acc = accuracy_score(y_test, y_pred2)
print(f'Gradient Boosting Accuracy: {gradient_acc:.4f}')
print(classification_report(y_test, y_pred2))

Gradient Boosting Accuracy: 0.8675
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000



In [19]:
print(f"Logistic Regression ROC AUC: {roc_auc_score(y_test, y_pred0):.4f}")
print(f"Random Forest ROC AUC: {roc_auc_score(y_test, y_pred1):.4f}")
print(f"Gradient Boosting ROC AUC: {roc_auc_score(y_test, y_pred2):.4f}")

Logistic Regression ROC AUC: 0.5806
Random Forest ROC AUC: 0.7151
Gradient Boosting ROC AUC: 0.7244


In [20]:
print("Confusion Matrix for Logistic Regression:")
print(confusion_matrix(y_test, y_pred0))
print("Confusion Matrix for Random Forest:")
print(confusion_matrix(y_test, y_pred1))
print("Confusion Matrix for Gradient Boosting:")
print(confusion_matrix(y_test, y_pred2))

Confusion Matrix for Logistic Regression:
[[1543   64]
 [ 314   79]]
Confusion Matrix for Random Forest:
[[1550   57]
 [ 210  183]]
Confusion Matrix for Gradient Boosting:
[[1543   64]
 [ 201  192]]
